on:
  workflow_call:
    inputs:
      config-path: 
        required: true
        type: string
      
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@v2.3.9

  dart-scan:
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - uses: actions/checkout@v3
      - name: 🔍 Flutter / Dart Scanner
        uses: affinidi/dart-pipeline-scanner/.github/actions/dart-scan@main
        with:
          repo-path: '${{ inputs.config-path }}'
          DART_SCANNER_TOKEN: ${{ secrets.DART_SCANNER_TOKEN }}
          DART_SCANNER_REGION: ${{ secrets.DART_SCANNER_REGION }}