on:
  workflow_call:
    inputs:
      config-path: 
        required: true
        type: string
    secrets: inherit
      
jobs:
# secret detection security scanner
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@latest
